# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

begin
  Rake::Task[:spec].clear
  require 'rake'
  require 'rspec/core/rake_task'
  task :test do
   RSpec::Core::RakeTask.new(:rawr) do |t|
        t.pattern = "./spec/*.rb"
        t.fail_on_error = false
        t.rspec_opts = "--format documentation"
        t.verbose = false
    end
    Rake::Task[:rawr].execute
  end
  task :default => :test
rescue LoadError
  # no rspec available
end
