# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require_relative 'config/application'

Rails.application.load_tasks

begin
  require 'rspec/core/rake_task'

   RSpec::Core::RakeTask.new(:local_spec) do |t|
        t.pattern = "./spec/*.rb"
        t.fail_on_error = false
        t.rspec_opts = "--format documentation"
        t.verbose = false
    end

  task :default => :local_spec
rescue LoadError
  # no rspec available
end
